### ISSUE TITLE
Add an Open Source License

### ISSUE THREAD

**Issue by fer-correa** [tiaguinho/cli-bud#2]
Hi @tiaguinho, how are you?
I just saw your post on LinkedIn, where you mention the project being Open Source... but as it doesn't have an **open source license**, it's not actually open source.

Could you add an open source license to the project? If you opt for a permissive license (**MIT**, for example) you may even attract more people from the community.

Thanks and congrats!!!

**Comment by tiaguinho** [comment]
Thank you for spotting this.

I just add the MIT license.
